[pytest]
#python_paths =
#    /root/appdaemon-testing
#    /root/appdaemon-testing/appdaemon_testing
#    /root/appdaemon
#    /root/appdaemon/appdaemon/plugins/hass
#    /addon_configs/a0d7b954_appdaemon/apps
