automationlib:
  module: automationlib
  global: true

# test:
#   module: test
#   class: Test
#   dependencies:
#     - automationlib

announcer:
  module: announcer
  class: Announcer
  dependencies:
    - automationlib

automation:
  module: automation
  class: Automation
  dependencies:
    - automationlib
    - announcer

alarms:
  module: alarms
  class: Alarms
  # log_level: DEBUG
  dependencies:
    - automationlib
    - announcer

starling:
  module: starling
  class: Starling
  dependencies:
    - automationlib
    - announcer

sonos:
  module: sonos
  class: Sonos
  dependencies:
    - automationlib
    - announcer

location:
  module: location
  class: Location
  dependencies:
    - automationlib
    - announcer

weather:
  module: weather
  class: Weather
  # log_level: DEBUG
  # location: 78704 US
