automationlib:
  module: automationlib
  class: AutomationLib
  log_level: DEBUG

automation:
  module: automation
  class: Automation
  log_level: DEBUG
  dependencies:
    - automationlib
    - announcer
    - timestamp
    - motion
    - lighting
    - timers
    - location
    - alarms
    - sonos
    - garage
    - weather
    - tap
    - vacuum
    - shelly
    # - fan
    # - doorbell
    # - front_door
    # - starling
    # - car

announcer:
  module: announcer
  class: Announcer
  log_level: DEBUG
  dependencies: # timestamp causes cyclic dependency
    - automationlib

timestamp:
  module: timestamp
  class: Timestamp
  log_level: DEBUG
  dependencies:
    - automationlib
    - announcer

motion:
  module: motion
  class: Motion
  reset_on_off: false
  log_level: DEBUG
  dependencies:
    - automationlib
    - announcer
    - timestamp

lighting:
  module: lighting
  class: Lighting
  log_level: DEBUG
  dependencies:
    - automationlib
    - announcer
    - timestamp

timers:
  module: timers
  class: Timers
  log_level: DEBUG
  dependencies:
    - automationlib
    - announcer
    - timestamp

location:
  module: location
  class: Location
  log_level: DEBUG
  dependencies:
    - automationlib
    - announcer
    - timestamp
    - lighting

alarms:
  module: alarms
  class: Alarms
  log_level: DEBUG
  dependencies:
    - automationlib
    - announcer
    - timestamp

sonos:
  module: sonos
  class: Sonos
  log_level: DEBUG
  dependencies:
    - automationlib
    - announcer
    - timestamp

garage:
  module: garage
  class: Garage
  log_level: DEBUG
  dependencies:
    - automationlib
    - announcer
    - timestamp

weather:
  module: weather
  class: Weather
  log_level: DEBUG
  # location: 78704 US
  dependencies:
    - announcer

tap:
  module: tap
  class: Tap
  log_level: DEBUG
  dependencies:
    - automationlib
    - announcer
    - timestamp

vacuum:
  module: vacuum
  class: Vacuum
  log_level: DEBUG
  dependencies:
    - automationlib
    - announcer
    - timestamp

shelly:
  module: shelly
  class: Shelly
  log_level: DEBUG
  dependencies:
    - automationlib
    - announcer
    - timestamp

snoozer:
  module: snoozer
  class: Snoozer
  log_level: DEBUG
  dependencies:
    - automationlib
    - announcer
    - timestamp

# fan:
#   module: fan
#   class: Fan
#   log_level: DEBUG
#   dependencies:
#     - announcer
#     - timestamp

# # --
# doorbell:
#   module: doorbell
#   class: DoorBell
#   log_level: DEBUG
#   dependencies:
#     - announcer
#

# front_door:
#   module: front_door
#   class: FrontDoor
#   log_level: DEBUG
#   dependencies:
#     - announcer
#     - timestamp

# starling:
#   module: starling
#   class: Starling
#   log_level: DEBUG
#   dependencies:
#     - announcer
#
# car:
#   module: car
#   class: Car
#   log_level: DEBUG
#   dependencies:
#     - announcer
#     - timestamp
